# Generated by Django 3.2.3 on 2023-06-26 15:50
from django.db import migrations
import csv
from recipes.models import Ingredient, Tag


def insert_ingridients(apps, schema_editor):
    with open('data/ingredients.csv',
              encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            try:
                name, measurement_unit = row
                Ingredient.objects.get_or_create(
                    name=name,
                    measurement_unit=measurement_unit)
            except Exception as error:
                print(row)
                print(f'Ошибка записи в таблицу Ingredients {str(error)}')


def insert_tags(apps, schema_editor):
    Tag.objects.get_or_create(name='Завтрак', slug='breakfast',
                              color='#FF0000')
    Tag.objects.get_or_create(name='Обед', slug='lunch', color='#CC0000')
    Tag.objects.get_or_create(name='Ужин', slug='dinner', color='#660000')


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_ingridients),
        migrations.RunPython(insert_tags),
    ]
